# Site settings
title: Arizona Karen Baptist Church.
email: admin@akbc.us
description: > # this means to ignore newlines until "baseurl:"
    Arizona Karen Baptist Church.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://akbc.us" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

include: ['_pages']

sass:
    style: compressed
